### ISSUE TITLE
Gk6x can using qmk?

### ISSUE THREAD

**Issue by 1ocate** [ukeloop/gk6x_gui#1]
Hi thank you for made great project, and finally I have perfect keyboard.

Sorry this is not issue just question.

I'm confuse gk6x keyboards can use ymk or not.
My searching ability  maybe not well

I found your write in your project 
"If you want to make more advanced settings, use a PCB that supports QMK Firmware, such as DZ60RBG."

It is true? I can't see any information.. if you success please little bit teach  how in to mode DFU (reset button where..?).

Thank you  again for your great job.
Have a nice day.

**Comment by ukeloop** [comment]
Hi 1ocate.

GK6X keyboards don't support QMK Firmware.
You need the PCB with QMK Firmware support if you want to have a comfortable keyboard life.

QMK allows you to customize your keyboard with a C or GUI Tools.
You can se t up Combos, Tap Dance, Tap-Hold, etc.
And Add Advanced modules on your keyboard.

I bred Digimon with the my Corne Keyboard. 
[ukeloop/crkbd-digimon-oled](https://github.com/ukeloop/crkbd-digimon-oled)

**Comment by 1ocate** [comment]
Thank you @ukeloop.

I tought maybe DZ60RBG relation with gk6x. 

Now I know why PCB different price...

I just know about qmk and this world..

Thank you again.
