### ISSUE TITLE
Dropdown menus are uncomfortable...

### ISSUE THREAD

**Issue by veronikazaglotova** [ukeloop/gk6x_gui#5]
IMO would be better if it acted like the official software, e.g. choose layer - click button - choose what it does. What we have now is just redundant, each time I have to choose the right dropdown menu. IDK about you but I don't edit a key on several layers, I edit several keys on the same layer.

**Comment by ukeloop** [comment]
If you enter any keys on dropdown, choices will become narrower.

**Comment by veronikazaglotova** [comment]
Yeah but still, typing is inconvenient. IMO a good design of keyboard layout customization is https://config.qmk.fm

**Comment by ukeloop** [comment]
I'll refer to it if I ever recreate it again.
